name: FlyCredits
version: 0.6
author: LadyProxima
main: me.ladyproxima.flycredits.FlyCredits
api-version: 1.12.2
depend:
- Vault
commands:
  fc:
    description: Give users time to fly.
    usage: |
      Usage:
      /fc add <user> <duration> <world>
      /fc remove <user> <duration> <world>
      /fc check [<user>]
      /fc checkall

permissions:
  flycredits.use:
    description: Allows addition and removal of FlyCredits.
    default: op
  flycredits.check:
    description: Allows fc check command.
    default: op
  flycredits.bypass:
    description: Allows bypassing of flight-disable on world change.
    default: op